#                                                                        #
# Default routes configuration for the CaP package                       #
#                                                                        #

-
  name: 'Standard route'
  uriPattern: ''
  defaults:
    '@package':    'CaP'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
