#                                                                        #
# Default routes configuration for the CaP package                       #
#                                                                        #
# origin: M                                                              #

-
  name:          'Frontend: /login'

  uriPattern:    'login'
  defaults:
    '@package':    'CaP'
    '@controller': 'Login'
    '@action':     'index'

-
  name:          'Frontend: /account/registration'

  uriPattern:    'account/registration'
  defaults:
    '@package':    'CaP'
    '@controller': 'Registration'
    '@action':     'index'

-
  name:          'Frontend: /conferences/category/{category}'

  uriPattern:    'conferences/category/{category}'
  defaults:
    '@package':    'CaP'
    '@controller': 'Conference'
    '@action':     'index'
  routeParts:
    category:
      handler:    F3\CaP\Routing\CategoryRoutePartHandler

-
  name:          'Frontend: /conferences/{conference}'

  uriPattern:    'conferences/{conference}'
  defaults:
    '@package':    'CaP'
    '@controller': 'Conference'
    '@action':     'show'
  routeParts:
    conference:
      handler:    F3\CaP\Routing\ConferenceRoutePartHandler

-
  name:          'Frontend: /conferences'

  uriPattern:    'conferences'
  defaults:
    '@package':    'CaP'
    '@controller': 'Conference'
    '@action':     'index'

##
# REST services

-
  name:          'REST: /conferences/{conference}'

  uriPattern:    'ws/conferences/{conference}'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Conference'
    '@format':     'json'
    '@action':     'show'
  routeParts:
    conference:
      handler:    F3\CaP\Routing\ConferenceRoutePartHandler

-
  name:          'REST: /conferencesbycategory/{category}'

  uriPattern:    'ws/conferencesbycategory/{category}'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Conference'
    '@format':     'json'
    '@action':     'listByCategory'
  routeParts:
    category:
      handler:    F3\CaP\Routing\CategoryRoutePartHandler

-
  name:          'REST: /conferences'

  uriPattern:    'ws/conferences'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Conference'
    '@format':     'json'

-
  name:          'REST: /categories/{category}'

  uriPattern:    'ws/categories/{category}'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Category'
    '@format':     'json'
    '@action':     'show'
  routeParts:
    category:
      handler:    F3\CaP\Routing\CategoryRoutePartHandler

-
  name:          'REST: /categories'

  uriPattern:    'ws/categories'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Category'
    '@format':     'json'

-
  name:          'REST: /reset'

  uriPattern:    'ws/reset'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Reset'
    '@format':     'json'

-
  name:          'REST: /factorydefaults'

  uriPattern:    'ws/factorydefaults'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'FactoryDefaults'
    '@format':     'json'

##
# Fallback

-
  name: 'Standard route'
  uriPattern: ''
  defaults:
    '@package':    'CaP'
    '@controller': 'Conference'
    '@action':     'index'
    '@format':     'html'

