#                                                                        #
# Default routes configuration for the CaP package                       #
#                                                                        #
# origin: M                                                              #

# FRONTEND

-
  name:          'Frontend: /setup'

  uriPattern:    'setup'
  defaults:
    '@package':    'CaP'
    '@controller': 'Setup'
    '@action':     'index'
    '@format':     'html'

-
  name:          'Frontend: /logout'

  uriPattern:    'logout'
  defaults:
    '@package':    'CaP'
    '@controller': 'Login'
    '@action':     'logout'
    '@format':     'html'

-
  name:          'Frontend: /login(/{@action})'

  uriPattern:    'login(/{@action})'
  defaults:
    '@package':    'CaP'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'

-
  name:          'Frontend: /members/registration'

  uriPattern:    'members/registration(/{@action})'
  defaults:
    '@package':    'CaP'
    '@subpackage': ''
    '@controller': 'Registration'
    '@action':     'index'
    '@format':     'html'

-
  name:          'Frontend: /members/status/{member}'

  uriPattern:    'members/status/{member}'
  defaults:
    '@package':    'CaP'
    '@subpackage': ''
    '@controller': 'Member'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    member:
      handler:    F3\CaP\Routing\MemberRoutePartHandler

-
  name:          'Frontend: /members'

  uriPattern:    'members'
  defaults:
    '@package':    'CaP'
    '@subpackage': ''
    '@controller': 'Member'
    '@action':     'index'
    '@format':     'html'

-
  name:          'Frontend: /conferences/category/{category}'

  uriPattern:    'conferences/category/{category}'
  defaults:
    '@package':    'CaP'
    '@subpackage': ''
    '@controller': 'Conference'
    '@action':     'index'
    '@format':     'html'
  routeParts:
    category:
      handler:    F3\CaP\Routing\CategoryRoutePartHandler

-
  name:          'Frontend: /conferences/{conference}'

  uriPattern:    'conferences/{conference}'
  defaults:
    '@package':    'CaP'
    '@subpackage': ''
    '@controller': 'Conference'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    conference:
      handler:    F3\CaP\Routing\ConferenceRoutePartHandler

-
  name:          'Frontend: /conferences(/{@action})'

  uriPattern:    'conferences(/{@action})'
  defaults:
    '@package':    'CaP'
    '@subpackage': ''
    '@controller': 'Conference'
    '@action':     'index'
    '@format':     'html'

##
# REST services

-
  name:          'REST: /conferencesbycategory/{category}'

  uriPattern:    'ws/conferencesbycategory/{category}'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Conference'
    '@format':     'json'
    '@action':     'listByCategory'
  routeParts:
    category:
      handler:    F3\CaP\Routing\CategoryRoutePartHandler

-
  name:          'REST: /conferences/{conference}'

  uriPattern:    'ws/conferences/{conference}'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Conference'
    '@format':     'json'
    '@action':     'show'
  routeParts:
    conference:
      handler:    F3\CaP\Routing\ConferenceRoutePartHandler

-
  name:          'REST: /conferences'

  uriPattern:    'ws/conferences'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Conference'
    '@format':     'json'

-
  name:          'REST: /members/{member}'

  uriPattern:    'ws/members/{member}'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Member'
    '@format':     'json'
    '@action':     'show'
  routeParts:
    member:
      handler:    F3\CaP\Routing\MemberRoutePartHandler

-
  name:          'REST: /categories/{category}'

  uriPattern:    'ws/categories/{category}'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Category'
    '@format':     'json'
    '@action':     'show'
  routeParts:
    category:
      handler:    F3\CaP\Routing\CategoryRoutePartHandler

-
  name:          'REST: /categories'

  uriPattern:    'ws/categories'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Category'
    '@format':     'json'

-
  name:          'REST: /reset'

  uriPattern:    'ws/reset'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Reset'
    '@format':     'json'

-
  name:          'REST: /factorydefaults'

  uriPattern:    'ws/factorydefaults'
  defaults:
    '@package':    'CaP'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'FactoryDefaults'
    '@format':     'json'

##
# Fallback

-
  name: 'Standard route'
  uriPattern: ''
  defaults:
    '@package':    'CaP'
    '@controller': 'Conference'
    '@action':     'index'
    '@format':     'html'

