#                                                                        #
# Configuration for the FLOW3 Framework                                  #
#                                                                        #
# This file contains the default base configuration for the FLOW3        #
# Framework. Don't modify this file but add configuration options to     #
# the FLOW3.yaml file in the in global Configuration/ directory instead. #
#                                                                        #

# @package FLOW3
# @origin M

FLOW3:
  security:
    authentication:

      providers:
        DefaultProvider:
          providerClass: PersistedUsernamePasswordProvider
          useTokenClass: F3\FLOW3\Security\Authentication\Token\UsernamePassword
          requestPatterns:
            controllerObjectName: 'F3\CaP\Controller\.*Controller'
          entryPoint:
            webRedirect:
              uri: login

        RESTServiceProvider:
          providerClass: PersistedUsernamePasswordProvider
          useTokenClass: F3\FLOW3\Security\Authentication\Token\UsernamePasswordHTTPBasic
          requestPatterns:
            controllerObjectName: 'F3\CaP\Service\Rest\V1\Controller\.*Controller'
          entryPoint:
            HTTPBasic:
              realm: "Authenticate for the REST services"

      authenticationStrategy: atLeastOneToken